title: for.theloveof.house
description:  A redirect site for https://for.theloveof.house.

repository: DidierMalenfant/for.theloveof.house

exclude:
  - bin
  - CNAME
  - README.md

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: atom.xml

permalink: :title

defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: :year/:month/:day/:title/
  - scope:
      path: ""

github:
  repository_nwo: DidierMalenfant/for.theloveof.house
